; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:OpenRB-150]
platform = atmelsam
platform_packages = platformio/tool-bossac@1.10901.0
board = OpenRB-150
framework = arduino
lib_deps = 
  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git
  waspinator/AccelStepper
upload_protocol = sam-ba
upload_command = "C:\Users\marco\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.7.0-arduino3\bossac.exe" --port=$UPLOAD_PORT -U true -e -w -v -R .pio\build\OpenRB-150\firmware.bin
src_filter = +<OpenRB-150.cpp> -<main.cpp> -<main_without_dynamixel.cpp> -<Test_Pince.cpp>
;src_filter = +<Test_Pince.cpp> -<main.cpp> -<main_without_dynamixel.cpp> -<OpenRB-150.cpp>

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git
  waspinator/AccelStepper
src_filter = +<main_without_dynamixel.cpp> -<main.cpp> -<OpenRB-150.cpp> -<Test_Pince.cpp>

