; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:OpenRB-150]
;platform = atmelsam
;platform_packages = platformio/tool-bossac@1.10901.0
;board = OpenRB-150
;framework = arduino
;lib_deps = 
;  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git
;  waspinator/AccelStepper
;upload_protocol = sam-ba
;upload_command = "C:\Users\marco\AppData\Local\Arduino15\packages\arduino\tools\bossac\1.7.0-arduino3\bossac.exe" --port=$UPLOAD_PORT -U true -e -w -v -R .pio\build\OpenRB-150\firmware.bin

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/ROBOTIS-GIT/Dynamixel2Arduino.git
  waspinator/AccelStepper
  ArduinoJson
  adafruit/Adafruit NeoPixel@^1.15.4
build_src_filter = -<TestMotor.cpp> -<test_Comm_mega.cpp> -<TestBouton.cpp> -<main_without_dynamixel.cpp> -<OpenRB-150.cpp> -<Test_Pince.cpp> -<test_ISR.cpp> -<test_AxeZ_et_Pince.cpp> +<main_with_dynamixel.cpp>
